image: docker

variables:
  IMAGE_TAG: "${CI_PROJECT_ID}-${CI_COMMIT_SHA}"

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t "$IMAGE_TAG" .
    - docker image rm -f "$IMAGE_TAG"

